[package]
authors = ["workoss <workoss@icloud.com>"]
categories = ["wasm"]
edition = "2021"
license = "Apache-2.0"
name = "wasi-http-demo"
repository = "http://git.workoss.com:3000/workoss/demo"
version = "0.0.1"

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "wasi:wasi-http-demo"
proxy = true

[dependencies]
wit-bindgen-rt = {version = "0.39", features = ["bitflags"]}
wstd = "0.5"

[profile.release]
codegen-units = 1 # Allows LLVM to perform better optimization.
debug = false # Disables debug information.
incremental = false # Disables incremental compilation.
lto = true # Enables link-time-optimizations.
opt-level = "s" # Prioritizes small binary size. Use `3` if you prefer speed.
panic = "abort" # Higher performance by disabling panic handlers. 
strip = true # Ensures debug symbols are removed.
