# cargo-features = ["profile-rustflags", "trim-paths"]
[workspace]
exclude = ["crates/wasi-http-demo"]
members = [
  "crates/demo-cli",
  "crates/javy_demo_plugin",
  "crates/axum_demo",
  "crates/proc",
  "crates/proc-demo",
  "crates/uniffi-demo",
]
resolver = "3"

[workspace.package]
authors = ["workoss <workoss@icloud.com>"]
categories = ["wasm"]
edition = "2024"
license = "Apache-2.0"
repository = "http://git.workoss.com:3000/workoss/demo"
version = "0.0.1"

[workspace.dependencies]
anyhow = {version = "1.0"}

[profile.dev]
incremental = true # Compile your binary in smaller steps.
# rustflags = ["-Zthreads=8"] # Better compile performance.            

[profile.release]
codegen-units = 1 # Allows LLVM to perform better optimization.
debug = false # Disables debug information.
incremental = false # Disables incremental compilation.
lto = true # Enables link-time-optimizations.
opt-level = "s" # Prioritizes small binary size. Use `3` if you prefer speed.
panic = "abort" # Higher performance by disabling panic handlers.
# rustflags = ["-Cdebuginfo=0", "-Zthreads=8"] # Better compile performance.            
strip = true # Ensures debug symbols are removed.
# trim-paths = "all" # Removes potentially privileged information from your binaries.
