[package]
authors.workspace = true
edition.workspace = true
license.workspace = true
name = "proc"
version.workspace = true

[lib]
path = "src/lib.rs"
# proc-macro = true

[dependencies]
quote = {version = "1.0"}
