[package]
authors.workspace = true
categories.workspace = true
edition = "2021"
license.workspace = true
name = "wasm_plugin_api"
repository.workspace = true
version.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
anyhow.workspace = true
wit-bindgen = "0.35"

[package.metadata.component]
target = {path = "wit"}
